logging: #logback config
  config: classpath:logback-spring.xml
  file: logs/spring-boot.log
  level.: info
  
server: #server config
  port: 8080
  
spring:
  main: #spring boot config
    banner-mode: "off" #关闭banner
    
  datasource: #data source config
    url: jdbc:mysql://127.0.0.1:3306/gjf?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    initScriptFile: /sql/init.sql
    
  jpa: #jpa config
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      
  messages: #i18n config
    basename: i18n/messages
   
  thymeleaf: #thymeleaf config
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false